#!/usr/bin/env bash
# GitHub issue creation for spec compliance review.
# Separated from lib/spec-review.sh for file size management.
# Must be sourced from spec-review.sh (not standalone) — uses constants defined there.

# Guard against double-sourcing.
[[ -n "${_AUTOPILOT_SPEC_REVIEW_ISSUE_LOADED:-}" ]] && return 0
readonly _AUTOPILOT_SPEC_REVIEW_ISSUE_LOADED=1

# Build the GitHub issue body for spec review findings.
_build_issue_body() {
  local task_number="$1"
  local review_output="$2"

  cat <<EOF
## Spec Compliance Review — After Task ${task_number}

This automated review checked the last ${_SPEC_REVIEW_PR_COUNT} merged PRs against the project specification.

### Findings

${review_output}

---
*Generated by autopilot spec review*
EOF
}

# Create a GitHub issue with spec review findings.
_create_review_issue() {
  local project_dir="$1"
  local repo="$2"
  local task_number="$3"
  local review_output="$4"
  local timeout_gh="${AUTOPILOT_TIMEOUT_GH:-30}"
  local max_body="${_SPEC_REVIEW_MAX_BODY_LENGTH}"

  # Sanitize: strip @mentions to prevent pings, truncate.
  review_output="${review_output//@/at-}"
  review_output="${review_output:0:$max_body}"

  local title="Spec compliance review: deviations found after task ${task_number}"
  local body
  body="$(_build_issue_body "$task_number" "$review_output")"

  # Try with label first, fall back without.
  if timeout "$timeout_gh" gh issue create --repo "$repo" \
      --title "$title" --body "$body" \
      --label "spec-review" 2>/dev/null; then
    log_msg "$project_dir" "INFO" \
      "Created spec review issue after task ${task_number}"
    return 0
  fi

  if timeout "$timeout_gh" gh issue create --repo "$repo" \
      --title "$title" --body "$body" 2>/dev/null; then
    log_msg "$project_dir" "INFO" \
      "Created spec review issue after task ${task_number} (no label)"
    return 0
  fi

  log_msg "$project_dir" "ERROR" \
    "Failed to create spec review issue after task ${task_number}"
  return 1
}
